### ISSUE TITLE
FE 벨리데이션, 값 체크

### ISSUE THREAD

**Issue by Nuung** [Zih0/coffee-hanzan#4]
- 소셜 연결에서 값 체크 (이메일 값 넣기나 또는 full url을 넣는 경우) 있으면 좋을 것 같아요
<img width="451" alt="image" src="https://user-images.githubusercontent.com/33516349/169541244-8beb0e60-e6ea-4f6f-a839-43822681236a.png">
  - 아니면 git 을 예시로 유저 검색이랑 연동을 좀 해서 해당 결과 값 내에서만 선택이 되게 하는 것이 정확한 값 체크가 가능할 것 같습니다!

**Comment by Zih0** [comment]
와! 피드백 감사합니다!!!! 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️
